encoding: UTF-8
title: jBPM - Open Source Business Process Management
description: jBPM is a flexible Business Process Management (BPM) Suite.
keywords: metaheuristic, heuristic, constraint satisfaction, constraint programming, operations research, NP-complete, NP-hard, optimization, planning, scheduling, java, open source, software, library, solver, tabu search, simulated annealing, pareto
canonicalBaseUrl: https://www.jbpm.org
issueTracker: https://issues.jboss.org/projects/JBPM

# jbossorg_bootstrap_css: http://static.jboss.org/theme/css/bootstrap/2.1.0.0.0/bootstrap-community.css
# jbossorg_bootstrap_js: http://static.jboss.org/theme/js/libs/bootstrap/2.1.0.0.0/bootstrap-community.js

googleAnalyticsId: UA-54014107-1
disqus: jbpm
disqus_generate_id: true

asciidoctor:
  :safe: safe
  :attributes:
    imagesdir: ''

# Avoid broken images in blog posts
generation:
  :in_threads: 0

profiles:
  development:
    developmentMode: true
  production:
    developmentMode: false
    base_url: https://www.jbpm.org
    deploy:
      host: jbpm@filemgmt.jboss.org
      path: /www_htdocs/jbpm/
